### ISSUE TITLE
Duplicated polyfills if polyfill is available in an assembly which has InternalsVisibleTo set

### ISSUE THREAD

**Issue by latonz** [meziantou/Meziantou.Polyfill#2]
If an assembly has `InternalsVisibleTo` set to another assembly, and `Meziantou.Polyfill` is added to both projects, polyfills are generated for both. This leads to duplicated types.

Eg (Assembly 1 has `InternalsVisibleTo("Assembly 2")`):
> The type 'CallerArgumentExpressionAttribute' exists in both '<Assembly 1>'  and `<Assembly 2>`.

Reproduction steps:
* Create a solution with 2 projects
* Add `Meziantou.Polyfill` to a `Directory.Build.props` in the solutions directory
* Set language version to 11.0 in the `Directory.Build.props`
* Set an older tfm (eg. `netstandard2.0`) in the `Directory.Build.props`
* Add a project reference from project 1 to project 2.
* Add `[assembly: InternalsVisibleTo("Project2")]` to the first project
* Build the solution

**Comment by meziantou** [comment]
Can you provide a repro project (zip or github repo)? On my side it seems to be supported. You can see that ClassLib2 doesn't contain any generated files.

<img width="397" alt="image" src="https://github.com/meziantou/Meziantou.Polyfill/assets/509220/eb444b1f-21d9-4a70-b9cf-cdeb08c6d029">

**Comment by latonz** [comment]
Thank you for the fast response. I poked around and found out that `ClassLibrary2` used a later tfm `net7.0`, but `ClassLibrary1` had a tfm of `netstandard2.0`. I added `net7.0` as tfm to `ClassLibrary1` and it worked.
The problem was that `ClassLibrary1` had only `netstandard2.0` as tfm and therefore generated the polyfills while also having `InternalsVisibleTo` set for `ClassLibrary2`, but `ClassLibrary2` had those types already due to the later tfm. I'm not even sure if this can be fixed 🤔  Repro: https://github.com/latonz/duplicated-polyfill-repro

Btw: thank you for this great source generator and your interesting blog posts!

**Comment by meziantou** [comment]
Thanks for the repro. What you can do is to not generate the conflicting types if you don't use them:

````
<PropertyGroup>
  <MeziantouPolyfill_IncludedPolyfills>T:Type1;T:Type2;M:Member1</MeziantouPolyfill_IncludedPolyfills>
  <MeziantouPolyfill_ExcludedPolyfills>M:System.</MeziantouPolyfill_ExcludedPolyfills>
</PropertyGroup>
````

- The values are semi-colon separated values. It's a prefix comparison, `T:` matches all types, `T:System.Diagnostics.` matches all types starting with `System.Diagnostics.`.
- You can find all generated members in the generated `Debug.g.cs` file
- If you are not using Visual Studio, you can output the generated files using 
    ````
    <EmitCompilerGeneratedFiles>True</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
    ````

**Comment by latonz** [comment]
Thank you for your explanations. I'll try using multi-targeting which should work in my setup.
