### ISSUE TITLE
IncludedPolyfills only includes the first element

### ISSUE THREAD

**Issue by dotlogix** [meziantou/Meziantou.Polyfill#26]
### Version of the Meziantou.Polyfill NuGet package

1.0.28

### Description

I tried the whitelist option to only include a few polyfills.
For some reason only the first element is included.
```
<MeziantouPolyfill_IncludedPolyfills>T:System.Runtime.CompilerServices;T:System.Diagnostics.CodeAnalysis;T:System.Runtime.InteropServices;T:System.Memory</MeziantouPolyfill_IncludedPolyfills>
```

### Reproduction Steps

Create a project and add the source generator to it.
Add
```
<MeziantouPolyfill_IncludedPolyfills>T:System.Runtime.CompilerServices;T:System.Diagnostics.CodeAnalysis;T:System.Runtime.InteropServices;T:System.Memory</MeziantouPolyfill_IncludedPolyfills>
```
In a property group

### Other information

I am using Rider, maybe thats an unsupported IDE?

**Comment by meziantou** [comment]
I'm not sure to understand what's happening in this case. It's not a bug in the parsing of the string, so I guess it's a limitation of MSBuild and source generators.

I've added the support of the `|` separator in 1.0.28. You can now replace the property with

````
<MeziantouPolyfill_IncludedPolyfills>T:System.Runtime.CompilerServices|T:System.Diagnostics.CodeAnalysis|T:System.Runtime.InteropServices|T:System.Memory</MeziantouPolyfill_IncludedPolyfills>
````

Let me know if this fix your issue

**Comment by meziantou** [comment]
Note: the package will be available in a few minutes. nuget.org needs to index it first.

**Comment by dotlogix** [comment]
@meziantou so the latest version of the package is still 1.0.28 and even after a nuget cache clear I get the version without support for | could you maybe bump the version to 1.0.29 not sure you can actually update existing packages on nuget.

**Comment by meziantou** [comment]
My bad, I forgot to update the package version in the commit. The new package will be available soon

**Comment by meziantou** [comment]
The package is now on nuget. It needs to be indexed first, and it should be available in a few minutes

**Comment by dotlogix** [comment]
Works like a charm thank you <3

**Comment by dotlogix** [comment]
Seems like there are more issues apperantly "M: ..." filter options dont work as expected however "T: ..." work just fine any suggestions?
I tried "M:System.Linq" should I maybe open another issue for this one?
