### ISSUE TITLE
Simple Example ?

### ISSUE THREAD

**Issue by ignatandrei** [meziantou/Meziantou.Polyfill#27]
I am trying to add this Roslyn Source Generator to my list of RSCG with examples, https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG 

But I cannot understand the use . Could you make a simple example?
Thanks

**Comment by meziantou** [comment]
You can read more about this source generator at https://www.meziantou.net/polyfills-in-dotnet-to-ease-multi-targeting.htm

**Comment by ignatandrei** [comment]
Thanks, now I understand.

https://ignatandrei.github.io/RSCG_Examples/v2/docs/Meziantou.Polyfill
