### ISSUE TITLE
IncludedPolyfills with M: ... do not work as expected

### ISSUE THREAD

**Issue by dotlogix** [meziantou/Meziantou.Polyfill#28]
### Version of the Meziantou.Polyfill NuGet package

1.0.28

### Description

I tried to whitelist the M:System.Linq option to only include a few polyfills.
For some reason this does not work if I add M: without anything it includes all M: options correctly
```
<MeziantouPolyfill_IncludedPolyfills>M:System.Linq</MeziantouPolyfill_IncludedPolyfills>
```

### Reproduction Steps

Create a project and add the source generator to it.
Add
```
<MeziantouPolyfill_IncludedPolyfills>M:System.Linq</MeziantouPolyfill_IncludedPolyfills>
```
In a property group

**Comment by meziantou** [comment]
Fixed by https://github.com/meziantou/Meziantou.Polyfill/commit/99b75a6e175efc313ac866bb29e5519d25c1d76e
