### ISSUE TITLE
Add System.Collections.Generic.PriorityQueue<TElement, TPriority> polyfill

### ISSUE THREAD

**Issue by latonz** [meziantou/Meziantou.Polyfill#3]
Add a polyfill for the [System.Collections.Generic.PriorityQueue<TElement, TPriority>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.priorityqueue-2) added in .NET 6.0.

**Comment by meziantou** [comment]
The new package should be published by https://github.com/meziantou/Meziantou.Polyfill/actions/runs/5739987881
