### ISSUE TITLE
No overload for method 'GetHashCode' takes 1 arguments

### ISSUE THREAD

**Issue by Revan1985** [meziantou/Meziantou.Polyfill#33]
### Version of the Meziantou.Polyfill NuGet package

1.0.33

### Description

In the GetHashCode method, inside generated file T_System.Collections.Generic.ReferenceEqualityComparer.g.cs, method RuntimeHelpers.GetHashCode(obj!); returns a "No overload for method 'GetHashCode' takes 1 arguments", but navigating with F12 goes to the required overload. 

### Reproduction Steps

Any program netstandard 2.0

**Comment by meziantou** [comment]
I cannot reproduce the issue. Can you provide a simple repro?

I tried to create a simple netstandard2.0 class library and run `dotnet build`. It works on my machine.

````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<LangVersion>11</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill" Version="1.0.33">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
````

**Comment by Revan1985** [comment]
Hi, thank you for the info.
I will try again tomorrow, I am not able to provide a project to reproduce the issue...
Maybe I have missed some configurations...
Anyway, avoiding a complete generation (and using only needed methods/types), works

**Comment by Revan1985** [comment]
hmmm, I tested this a little more.
Seems that the library I am using cause some issue in my current project.
Can I reference a library that uses the Polyfill directly in a v4.7.2 dll, or need some more foresight using it?

**Comment by Revan1985** [comment]
Ok, I have tested it a little more than before...
I have found that this was my mistake.
I have mixed net472 and standard2.0 libraries references, and this causes a little mess...
If I use just netstandard2 libraries, called by a 472, it works fine
