### ISSUE TITLE
Generated code may use features not supported by the current language version.

### ISSUE THREAD

**Issue by RachelDavids** [meziantou/Meziantou.Polyfill#38]
### Version of the Meziantou.Polyfill NuGet package

1.0.38

### Description

Several of the generated sources contain "file" level accessibility which is not supported when LangVersion is set to 10.0

### Reproduction Steps

Set LangVersion to 10.0 within the project file.

Attempt a build.

Multiple errors
error CS8936: Feature 'file types' is not available in C# 10.0. Please use language version 11.0 or greater.

**Comment by meziantou** [comment]
Is there something that prevents you from using C# 11?

**Comment by RachelDavids** [comment]
Personally no - however, In the corporate environment I am currently restricted to version 10.0 (NET6.0)

**Comment by meziantou** [comment]
.NET 6 is out of support in about 6 months. I'm not sure I want to make changes to support it now, when anyway you'll have to update to .NET 8 very soon.

**Comment by dodexahedron** [comment]
For V2 I'd agree, but cutting compatibility for bugfixed releases of v1 with existing users is pretty un-good and can alienate users.

Existing applications in corporate environments might still be there several years from now, and us changing minimums kinda breaks the whole "maintenance mode" expectation.

**Comment by meziantou** [comment]
> Existing applications in corporate environments might still be there several years from now, and us changing minimums kinda breaks the whole "maintenance mode" expectation.

It would be a consideration if I were paid for this project. Providing support for C# 10 should not be complicated, but I don't want to waste my personal time on it.

As a workaround, you can disable the generation of the problematic symbols: https://github.com/meziantou/Meziantou.Polyfill?tab=readme-ov-file#customization

**Comment by meziantou** [comment]
Of course, you can also submit a PR to provide support for C# 10. I'll be happy to review it!

**Comment by dodexahedron** [comment]
You can ignore my comment anyway. I thought I was posting in a different project. 😅
